package com.ezderm.solution.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = false,onlyExplicitlyIncluded = true)
@ToString(callSuper = false)
@Schema(description = "Represents a doctor object")
public class DoctorDto {
	
	@NotNull
    @Schema(required = true, description = "Unique identifier for the user, generated by the database.")
    @EqualsAndHashCode.Include
    private Long id;

}
