package com.ezderm.solution.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.RequiredMode;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = false,onlyExplicitlyIncluded = true)
@ToString(callSuper = false)
@Schema(description = "Represents a doctor object")
@AllArgsConstructor
public class DoctorDto {
	
	@NotNull
    @Schema(requiredMode = RequiredMode.REQUIRED, description = "Unique identifier for the doctor, generated by the database.")
    @EqualsAndHashCode.Include
    private Long id;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "Username of the doctor.")
	private String username;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "First name of the user.")
	private String firstName;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "Last name of the user.")
	private String lastName;

}
