package com.ezderm.solution.dto;

import java.time.LocalDate;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.RequiredMode;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = false,onlyExplicitlyIncluded = true)
@ToString(callSuper = false)
@Schema(description = "Represents a patient object")
@AllArgsConstructor
public class PatientDto {

	@NotNull
    @Schema(requiredMode = RequiredMode.REQUIRED, description = "Unique identifier for the patient, generated by the database.")
    @EqualsAndHashCode.Include
    private Long id;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "FirstName of the patient.")
	private String firstName;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "MiddleName name of the patient.")
	private String middleName;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "Lastname of the patient.")
	private String lastName;
	@NotNull
	@Schema(requiredMode = RequiredMode.REQUIRED, description = "Date of Birth the patient.")
	private LocalDate dateOfBirth;
}
